apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    name: nginx-app
    app: nginx-app
spec:
  containers:
  - name: nginx-app
    image: nginx:latest
    ports:
      - containerPort: 80
